version: "3"

services:

  client_web:
    build: Web
    ports:
      - "4200:4200"
    volumes:
      - ./Web:/app/src
  server-app:
    build: Server
    ports:
      - "3000:3000"
    volumes:
      - ./Server:/app/src
    links:
      - database
  database:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"